[recwindow]: Title recording added, require added, check before notify added

diff --git a/recwindow b/recwindow
--- a/recwindow
+++ b/recwindow
@@ -22,42 +22,63 @@ VIDEO_NAME="$VIDEO_DIR/$VIDEO_FILE"
 PID_FILE=$0.pid
 NAM_FILE=$0.nam
 
-function start () {
-	PARAMS=`xwininfo | egrep 'Absolute|Width|Height' | awk -F: '{print $2}'`
-	if [[ -z $PARAMS ]]
-	then
-		echo "Не удалось получить параметры окна"
-		exit 1;
-	fi
-	VAL=(XOFF YOFF XW YH)
-	ENCODER_OPT="-video_size XWxYH -i :0.0+XOFF,YOFF"
-	NUM=0
+function require () {
+	for i in $@
+	do
+		if [[ -z $(which $i) ]]
+		then
+			echo "ERROR: $i not found" 1>&2
+		exit 1
+		fi
+	done
+}
+function parseWinInfo () {
+	PARAMS="$@"
+	ENCODER_OPT_TPL='XWxYH -i :0.0+XOFF,YOFF'
+	VAL=('XOFF' 'YOFF' 'XW' 'YH')
 	for i in $PARAMS
 	do
 		TMP=$i
-		if [[ ($NUM -ge 2) && ($(($TMP%2)) != 0) ]]
+		if [[ ($NUM -ge 2) && ($(( $TMP % 2 )) != 0) ]]
 		then
-		TMP=$(($TMP+1))
+			TMP=$(( $TMP + 1 ))
 		fi
-		ENCODER_OPT=$(echo $ENCODER_OPT | sed "s/${VAL[$NUM]}/$TMP/g")
-		let NUM+=1
+		ENCODER_OPT_TPL=$(echo $ENCODER_OPT_TPL | sed "s/${VAL[$NUM]}/$TMP/g")
+		NUM=$(( $NUM + 1 ))
 	done
+	echo $ENCODER_OPT_TPL
+}
+function getWinInfo () {
+	PARAMS=$(xwininfo -frame | egrep 'Absolute|Width|Height' | awk -F: '{print $2}')
+	if [[ -z $PARAMS ]]
+	then
+		echo 'Cannot get windows properties'
+		exit 2
+	fi
+	echo $PARAMS
+}
+function start () {
+	REGION=$(parseWinInfo $(getWinInfo))
+	ffmpeg -f alsa -i pulse -f x11grab -framerate 24 -show_region 1 \
+		-threads 4 -q 1 -bt 8000000 -b 8500000 -y -video_size $REGION \
+		$VIDEO_PATH & echo $! > $PID_FILE
 	echo $VIDEO_NAME > $NAM_FILE
-	ffmpeg -f alsa -i pulse -f x11grab -framerate 24 \
-	-show_region 1 $ENCODER_OPT -threads 4 -q 1 -bt 8000000 \
-	-b 8500000 -y $VIDEO_PATH & echo $! > $PID_FILE
 }
 function stop () {
 	kill -SIGQUIT $PID
 	rm -f $PID_FILE
-	VIDEO_NAME=$(cat $NAM_FILE)
+	VIDEO_NAME=$(cat $NAM_FILE 2>/dev/null)
 	VIDEO_PATH="$VIDEO_NAME.$VIDEO_EXT"
 	VIDEO_PATH_MP4="$VIDEO_NAME.mp4"
 	ffmpeg -i $VIDEO_PATH -acodec mp2 $VIDEO_PATH_MP4
-	notify-send "Converted" "$VIDEO_PATH_MP4"
+	if [ -e $VIDEO_PATH_MP4 ]
+	then
+		notify-send "Converted" "$VIDEO_PATH_MP4"
+	fi
 	rm -f $NAM_FILE
 }
-PID=$(cat $PID_FILE)
+require notify-send xwininfo nice egrep awk sed date
+PID=$(cat $PID_FILE 2>/dev/null)
 if [ -z $PID ]
 then
 	start
